Repository AnshSinghSonkhia/Coding-Keyboard-Shortcuts, pull requests merged in 2022-10, with the labels that each got.

#19 Update Gmail Keyboard Shortcuts.md
  Gmail Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#20 Update Mac Keyboard Shortcuts.md
  Mac Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#21 Added Keyboard Shortcuts in Excel
  Excel Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#22 Update Pycharm Shortcuts.md
  PyCharm Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#23 added Letters with Accent Grave
  Keyboard Shortcuts for International Characters.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#24 Added the Apostrophe Shortcuts
  Keyboard Shortcuts for International Characters.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#25 Updated the CARET Symbols
  Keyboard Shortcuts for International Characters.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#26 Updated CARET and Added TILDE Characters
  Keyboard Shortcuts for International Characters.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#29 Added Mac Keyboard Shortcuts.md
  Mac Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#27 Added Excel KeyBoard Shortcut
  Excel Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#28 Added excel shortcuts
  Excel Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#30 Formated Excel & Mac.
  Excel Keyboard Shortcuts.md
  Mac Keyboard Shortcuts.md
Labels: documentation, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#31 Added Colon Characters & Formatted Caret and Tilde
  Keyboard Shortcuts for International Characters.md
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#32 Added Unicode character for hexadecimal
  Keyboard Shortcuts for International Characters.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#33 Updated Context Actions in PyCharm
  PyCharm Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#34 added a new shortcut
  Mac Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#36 screenshot windows
  Windows Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#35 shortcuts updated in Windows Key and Youtube
  Windows Keyboard Shortcuts.md
  YouTube Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#37 Added Table Format
  PyCharm Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#38 Enhanced The Readme.md
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#39 Added more contributors...
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#40 Added 2 more contributors
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#41 Update README.md Added Contribution Appreciation
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#43 Updated 2 more functions
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#42 Update Youtube Keyboards Shortcut
  YouTube Keyboard Shortcuts.md
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#44 Added Cygnus 7 & one more function
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#45 Added Navigation Between Code Issues
  PyCharm Shortcuts.md
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#47 Update Mac Keyboard Shortcuts.md
  Mac Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#48 Update Windows Keyboard Shortcuts.md
  Android Studio Shortcuts.md
  Windows Keyboard Shortcuts.md
  YouTube Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#51 Added Shortcuts for Microsoft Word
  Microsoft Word Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#54 Added 2 more functions
  Windows Keyboard Shortcuts.md
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#55 Added Microsoft Word Shortcuts
  Microsoft Word Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#56 Created 10 VScode shortcuts for faster coding
  10 VS Code Shortcuts for Faster Coding.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#57 Create Shortcuts in Jupyter Notebook
  Shortcuts in Jupyter Notebook
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#59 Activate thesaurus in word
  Microsoft Word Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#60 Create Google-chrome-keyboard-Shortcuts
  Google-chrome-keyboard-Shortcuts
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#61 Update Google-chrome-keyboard-Shortcuts
  Google-chrome-keyboard-Shortcuts
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#63 Added to Mac shortcuts
  Mac Keyboard Shortcuts.md
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#64 Update PyCharm Shortcuts.md
  PyCharm Shortcuts.md
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#65 Added few shortcuts
  Gmail Keyboard Shortcuts.md
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#66 Update Mac Keyboard Shortcuts.md
  Mac Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#68 added new shortcut. Solution to #1
  Mac Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#69 📝 Added shortcut for Opening a New Incognito Window
  Google-chrome-keyboard-Shortcuts
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#71 Update IntelliJ Shortcuts.md
  IntelliJ Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#67 Update Android Studio Shortcuts.md
  Android Studio Shortcuts.md
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted, beginner-friendly, first-contribution

#76 Update and rename Google-chrome-keyboard-Shortcuts to Google-chrome-k…
  Google-chrome-keyboard-Shortcuts
  Google-chrome-keyboard-Shortcuts.md
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted, first-contribution

#75 Added VS Code Shortcut keys
  10 VS Code Shortcuts for Faster Coding.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#77 youtube shortcuts for 360 degree videos
  YouTube Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#79 Updated Android Studio Shortcuts.md
  Android Studio Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#80 Atom-Shortcuts
  Atom-Shortcuts.md
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted, beginner-friendly

#81 outlook_shortcut
  outlook_shortcut
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#82 Added 5 Useful VSCode shortcuts to improve your coding speed.md
  5 Useful VSCode shortcuts to improve your coding speed.md
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#83 Add Navigation keys Shortcut
  Android Studio Shortcuts.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted, beginner-friendly

#84 Github KeyBoard Shortcuts.md
  Github KeyBoard Shortcuts.md
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted, first-contribution

#85 Added Shortcut for home page and changed spelling
  Google-chrome-keyboard-Shortcuts.md
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted, beginner-friendly, first-contribution

#90 Useful-Shortcut-added
  VsCode_most_useful_shortcut.md
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#97 Ubuntu Keyboard Shortcuts.md
  Ubuntu Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#96 added shortcut of kali linux to already existing kali linux file
  Kali-Linux Shortcuts.md
Labels: hacktoberfest-accepted

#98 docs: added firefox keyboard shortcuts
  Firefox Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#102 Merged 3 file into one
  VS Code Shortcuts.md
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted, beginner-friendly, first-contribution

#103 Update Windows Keyboard Shortcuts.md
  Windows Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#114 Added new shortcut for Android Studio
  Android Studio Shortcuts.md
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted, beginner-friendly, first-contribution

#118 Intellij Ctrl+R shortcut added
  IntelliJ Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#123 Update Gmail Keyboard Shortcuts.md
  Gmail Keyboard Shortcuts.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted
